- name: Install Composer dependencies
  run: composer install --no-progress
  working-directory: Stonkspizza

- name: Run Linter (PHP Pint)
  run: ./vendor/bin/pint
  working-directory: Stonkspizza

- name: Run Tests
  run: php artisan test
  working-directory: Stonkspizza

- name: Install npm dependencies
  run: npm install
  working-directory: Stonkspizza

- name: Build frontend assets
  run: npm run build
  working-directory: Stonkspizza

- name: Run Migrations
  run: php artisan migrate --force
  working-directory: Stonkspizza
  env:
    APP_ENV: production
    DB_CONNECTION: sqlite
    DB_DATABASE: database/database.sqlite
