name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, xml, sqlite, tokenizer, curl, fileinfo
          tools: composer

      # 3️⃣ Set up Node.js (for Vite)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 4️⃣ Install backend dependencies
      - name: Install Composer dependencies
        working-directory: ./Stonkspizza
        run: composer install --no-progress --prefer-dist --no-interaction

      # 5️⃣ Install frontend dependencies and build
      - name: Install and Build Frontend
        working-directory: ./Stonkspizza
        run: |
          npm install
          npm run build  # 👈 must be build, not dev

      # 6️⃣ Copy environment and generate key
      - name: Set up .env file
        working-directory: ./Stonkspizza
        run: |
          cp .env.example .env
          php artisan key:generate

      # 7️⃣ Use SQLite for testing
      - name: Set up SQLite database
        working-directory: ./Stonkspizza
        run: |
          mkdir -p database
          touch database/database.sqlite

      # 8️⃣ Run migrations
      - name: Run Migrations
        working-directory: ./Stonkspizza
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      # 9️⃣ Run Laravel Tests
      - name: Run Laravel Tests
        working-directory: ./Stonkspizza
        run: php artisan test

      # 🔟 Optimize Laravel
      - name: Build / Optimize Laravel
        working-directory: ./Stonkspizza
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # 🧩 Create downloadable artifact
      - name: Create Release Build
        run: zip -r laravel_build.zip Stonkspizza
        shell: bash

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel_build
          path: laravel_build.zip
