name: Laravel DevOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.6
        ports:
          - 3306:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: stonkspizza
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, xml, mysql, tokenizer, curl, fileinfo
          coverage: none

      - name: Copy .env
        run: cp Stonkspizza/.env Stonkspizza/.env.testing

      - name: Generate Laravel App Key
        run: php artisan key:generate --env=testing
        working-directory: Stonkspizza
        env:
          APP_ENV: testing

      - name: Run Migrations
        run: php artisan migrate --force --env=testing
        working-directory: Stonkspizza
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: stonkspizza
          DB_USERNAME: root
          DB_PASSWORD: ''

      - name: Run Tests
        run: php artisan test --env=testing
        working-directory: Stonkspizza
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: stonkspizza
          DB_USERNAME: root
          DB_PASSWORD: ''
