name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  laravel-ci:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP with needed extensions
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, xml, sqlite, tokenizer, curl, fileinfo

      # 3️⃣ Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      # 4️⃣ Generate Laravel App Key
      - name: Generate Laravel App Key
        run: php artisan key:generate
        env:
          APP_ENV: testing

      # 5️⃣ Static analysis (PHPStan / Larastan)
      - name: Static Analysis
        run: vendor/bin/phpstan analyse --memory-limit=512M

      # 6️⃣ Set environment for dev/testing (SQLite)
      - name: Setup environment
        run: cp .env.testing .env

      # 7️⃣ Create SQLite file if it doesn't exist
      - name: Prepare SQLite database
        run: mkdir -p database && touch database/database.sqlite

      # 8️⃣ Run Laravel migrations
      - name: Run Migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      # 9️⃣ Run automated tests
      - name: Run Laravel Tests
        run: php artisan test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      # 🔟 Build / Prepare Release
      - name: Build / Release
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # 1️⃣1️⃣ Deploy Simulation
      - name: Deploy Application
        run: echo "Simulated deployment: app ready for production"
