name: Laravel DevOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.6
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MYSQL_DATABASE: stonkspizza
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Stap 1: Code uit GitHub halen
      - name: Checkout Code
        uses: actions/checkout@v3

      # Stap 2: PHP instellen
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, mysqli, pdo_mysql, openssl
          coverage: none

      # Stap 3: Composer dependencies installeren
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist
        working-directory: Stonkspizza

      # Stap 4: Environment configureren
      - name: Setup Environment
        run: |
          cp Stonkspizza/.env.example Stonkspizza/.env
          php artisan key:generate
        working-directory: Stonkspizza
        env:
          APP_KEY: base64:u9qofqPB0DIRYgKCF1yqwxUQqHGc3qVgajiL+I6ZaSA=
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: stonkspizza
          DB_USERNAME: root
          DB_PASSWORD: ''

      # Stap 5: Database migraties draaien
      - name: Run Migrations
        run: php artisan migrate --force
        working-directory: Stonkspizza
        env:
          APP_KEY: base64:u9qofqPB0DIRYgKCF1yqwxUQqHGc3qVgajiL+I6ZaSA=
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: stonkspizza
          DB_USERNAME: root
          DB_PASSWORD: ''

      # Stap 6: Tests uitvoeren
      - name: Run Tests
        run: php artisan test --verbose
        working-directory: Stonkspizza
        env:
          APP_KEY: base64:u9qofqPB0DIRYgKCF1yqwxUQqHGc3qVgajiL+I6ZaSA=
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: stonkspizza
          DB_USERNAME: root
          DB_PASSWORD: ''
