name: Laravel DevOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, sqlite, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run Linter (PHP Pint)
        run: ./vendor/bin/pint

      - name: Run Tests
        run: php artisan test

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Run Migrations
        run: php artisan migrate --force
        env:
          APP_ENV: production
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
